version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - forbidigo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print(f|ln)?$
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -QF*
        - -ST1003
        - -ST1016
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: main.go
      - linters:
          - forbidigo
        source: "nats-server: v%s"
      - linters:
          - forbidigo
        path: server/opts.go
      - linters:
          - forbidigo
        path: _test.go
    paths:
      - .github
      - doc
      - docker
      - logos
      - scripts
      - util
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - .github
      - doc
      - docker
      - logos
      - scripts
      - util
      - third_party$
      - builtin$
      - examples$
